name: Build and Push Custom n8n Image

on:
  schedule:
    - cron: '0 0 * * *'  # Midnight +0
  workflow_dispatch:

jobs:
  check-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sanitize repo slug
        uses: actions/github-script@v6
        id: repo_slug
        with:
          result-encoding: string
          script: return 'ghcr.io/${{ github.repository }}'.toLowerCase()

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run version check
        id: version
        run: |
          bash version-check.sh
          echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push custom n8n image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.repo_slug.outputs.result }}:latest
            ${{ steps.repo_slug.outputs.result }}:${{ steps.version.outputs.version }}

  notify-on-failure:
    runs-on: ubuntu-latest
    needs: check-and-build
    if: failure()
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate failure message
        run: |
          echo "## 🚨 Build failed for custom n8n Docker image" > .github/workflows/failure-message.md
          echo "Repository: ${{ github.repository }}" >> .github/workflows/failure-message.md
          echo "Branch: ${{ github.ref_name }}" >> .github/workflows/failure-message.md
          echo "Workflow: ${{ github.workflow }}" >> .github/workflows/failure-message.md
          echo "Run ID: ${{ github.run_id }}" >> .github/workflows/failure-message.md
          echo "" >> .github/workflows/failure-message.md
          echo "🔗 [View logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> .github/workflows/failure-message.md
          echo "" >> .github/workflows/failure-message.md
          echo "Please investigate and re-run the workflow if needed." >> .github/workflows/failure-message.md

      - name: Create issue on failure
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "🚨 Build failed for n8n image"
          content-filepath: .github/workflows/failure-message.md
          token: ${{ secrets.ISSUE_NOTIFY_TOKEN }}
          labels: build-failure